# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.hostname = 'scraperhub-warehouse'
  
  # Keep all ports open for now
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # No Port Mapping for now
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.56.10"

  # No public network for now
  # config.vm.network "public_network"


  # Provider
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
  
    # Customize the amount of memory & CPU on the VM:
    vb.memory = "2048"
    vb.cpus = 2
  end

  config.vm.provision "shell" do |bootstrap|
    bootstrap.path="./scripts/bootstrap.sh"
    bootstrap.privileged=true
  end
end
